### ISSUE TITLE
Add support for .pdb files

### ISSUE THREAD

**Issue by yllekz** [euan-forrester/save-file-converter#241]
Hey there, I have some ancient .pdb save files from Palm OS Game Boy emulators. Any chance that support could be added to convert them over to modern/standard formats?

**Comment by euan-forrester** [comment]
Can you please post one of these files here so I can take a look?

I have plans to make an Advanced tab: https://github.com/euan-forrester/save-file-converter/issues/167 and I'm curious if one of the tools I'm thinking about adding there will be able to do this.

**Comment by yllekz** [comment]
Sure, GitHub won't let me upload directly but I have a OneDrive link here: https://1drv.ms/u/s!Arp9XZavoR5Hh4dDDPTlGPQt6zO6SA?e=A6oHUj

**Comment by euan-forrester** [comment]
Yeah on github you have to compress a file before attaching it. I've added it here: 
[Kid Icarus - Of Myths and Monsters.pdb.zip](https://github.com/euan-forrester/save-file-converter/files/11326256/Kid.Icarus.-.Of.Myths.and.Monsters.pdb.zip)

Thanks! I took a quick look at that file and I think that the upcoming Advanced tab will be able to handle this.

**Comment by euan-forrester** [comment]
@yllekz I just put out the new Advanced tab and I tried out your file and it didn't work with the automatic header removal like I was hoping it would. Looking more closely, I think that may be a save state rather than an in-game save. You may be able to find an in-game save within that file by using https://savefileconverter.com/#/utilities/advanced?tab=slice, but you'll have to poke around inside the file to find it, and I can't help you further there.
